package com.topjohnwu.magisk.ui.events


object ViewEvent {

    const val BACK_PRESS = Int.MAX_VALUE
    const val NAVIGATION_SUPERUSER_PRESS = BACK_PRESS - 1
    const val DARK_MODE_PRESS = NAVIGATION_SUPERUSER_PRESS - 1
    const val NAVIGATION_INSTALL_EXT_MODULE = DARK_MODE_PRESS - 1
    const val NAVIGATION_INSTALL_MAGISK = NAVIGATION_INSTALL_EXT_MODULE - 1
    const val NAVIGATION_SELECT_BOOT = NAVIGATION_INSTALL_MAGISK - 1

}
